"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['AgSoft.py']
DATA_FILES = [('',['data'])]
OPTIONS = {'argv_emulation': True,
    'includes':['tkinter'],
    'iconfile': '/Users/amjadali/Desktop/AgSoft3/icon2.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    py_modules=['fileOpen','fileOpen2','firstFrame','runOptimum','showRslt','tables'],
    options={'py2app' : OPTIONS},
    setup_requires=['py2app'],
)
